

data:
	mkdir -p Data
	cd Data
	wget https://github.com/forero/abacus/raw/master/data/SDSS/SDSS_data_random_Planck15.txt
	mv SDSS_data_random_Planck15.txt Data/
	wget https://github.com/forero/abacus/raw/master/data/SDSS/SDSS_data_Planck15.txt
	mv SDSS_data_Planck15.txt Data/

clean:
	rm *~
	rm -r Data/
