PY_SCRIPT = calculating_multiple_beta_and_Nrand.py

all:
	python $(PY_SCRIPT)

clean:
	rm -rf figures/
	rm -rf random_catalogs/
	rm -rf full_catalogs/
	rm -rf xdl_beta_skeleton/
	rm -f progress.txt
	rm -f *~
